DEBUG = false

SCREEN_X  = 1920
SCREEN_Y  = 1080

TILE_SIZE = 32
TILES_PER_METER = 1

GRAVITY = 9.8 * TILE_SIZE * TILES_PER_METER
LINEAR_DAMPING = 0.2
JUMP_GRAVITY_SCALE = 0.4

PLAYER_JUMP_HEIGHT = 6 * TILE_SIZE
PLAYER_MOVE_SPEED = 4 * TILE_SIZE

DATA_SPACING = 4

CAMERA_RENDER_OFFSET = 20

PLAYER_FILENAME = "player"
MAP_FILENAME = "map"
ENTITIES_FILENAME = "entities_file"
SAVE_FOLDER = "world"

SPAWN_X = 0.5       -- Relative to world so on a scale of 0-1
SPAWN_Y = 0.1       -- Relative to world so on a scale of 0-1

PLAYER_WIDTH = TILE_SIZE * 0.8
PLAYER_HEIGHT = 2 * TILE_SIZE * 0.98

INTERACT_DISTANCE = 5

MAP_X = 1000
MAP_Y = 5000

PLAYER_CATEGORY = 2
BLOCKS_CATEGORY = 3
SPELLS_CATEGORY = 4
ENEMY_CATEGORY = 5

IN_WORLD_STATE = "IN_WORLD"
PICK_WORKD_STATE = "PICK_WORLD"
MENU_STATE = "MENU"